export const randomSets = {
  ru: "абвгдеёжзийклмнопрстуфхцчшщъыьюя",
  RU: "АБВГДЕЁЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЮЯ",
  en: "abcdefghijklmnopqrstuvwxyz",
  EN: "ABCDEFGHIJKLMNOPQRSTUVWXYZ",
  num: "0123456789",
  hex: "0123456789ABCDEF",
  sym: '!@#$%^&*()_+-=/{}:;",.?<> ',
};

export const randomNames = {
  vowels: "aeiouy",
  consonants: "bdghklmnprstv",
  normals: [2, 2],
};

export const randomEnNames = {
  vowels: "aeiou",
  consonants: "bcdfghklmnprstw",
  endings: [
    ["a", "ana", "e", "en", "er", "ia", "ie", "ina", "ine", "y", "yn"],
    [
      "ald",
      "an",
      "ard",
      "art",
      "arth",
      "arts",
      "e",
      "ech",
      "eck",
      "eld",
      "ell",
      "en",
      "er",
      "erd",
      "ert",
      "erts",
      "es",
      "ich",
      "ick",
      "ill",
      "in",
      "ith",
      "low",
      "man",
      "n",
      "och",
      "ock",
      "old",
      "oll",
      "or",
      "ord",
      "ort",
      "orth",
      "orts",
      "s",
      "son",
      "ton",
      "uch",
      "uck",
      "y",
    ],
  ],
};

export const randomRuNames = {
  vowels: "аеиоу",
  consonants: "бвгдзклмнпрстчш",
  endings: [
    [
      ["а", "ана", "ена", "ика", "ина", "ия", "яна"],
      [
        "ан",
        "ей",
        "ер",
        "еслав",
        "ил",
        "им",
        "имир",
        "ис",
        "ислав",
        "омир",
        "он",
        "ор",
        "ослав",
        "ур",
      ],
    ],
    [
      ["ова", "ева", "ян", "ич", "ко", "ман", "ная", "ер"],
      ["ев", "ин", "кий", "ко", "ман", "ный", "ов", "ян"],
    ],
    [
      ["евна", "овна"],
      ["евич", "ович"],
    ],
  ],
};
